//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicColorsSetEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicColorsSetEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Could not find \&quot;CpkMaker.dll!
        ///This is required to create and extract cpks..
        /// </summary>
        internal static string CPKMakerNotFoundText {
            get {
                return ResourceManager.GetString("CPKMakerNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find boot.dol!
        ///Make sure boot.dol is in the parent directory of &quot;sonic2010_0&quot;.
        /// </summary>
        internal static string DolNotFoundText {
            get {
                return ResourceManager.GetString("DolNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Dolphin!.
        /// </summary>
        internal static string DolphinNotFoundText {
            get {
                return ResourceManager.GetString("DolphinNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin is not set up yet!.
        /// </summary>
        internal static string DolphinNotSetupText {
            get {
                return ResourceManager.GetString("DolphinNotSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate your Dolphin executable..
        /// </summary>
        internal static string LocateDolphinText {
            get {
                return ResourceManager.GetString("LocateDolphinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate Sonic Colors&apos; executable..
        /// </summary>
        internal static string LocateSCExecutableText {
            get {
                return ResourceManager.GetString("LocateSCExecutableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more set files has been found
        ///Would you like to load one of the set files?.
        /// </summary>
        internal static string MultipleSetDataFoundText {
            get {
                return ResourceManager.GetString("MultipleSetDataFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Templates Found!
        ///Please download the Templates folder from HedgeLib&apos;s Github page
        ///and place it in the same directory as the executable
        ///https://github.com/Radfordhound/HedgeLib/tree/master/HedgeEdit/Templates.
        /// </summary>
        internal static string NoTemplatesText {
            get {
                return ResourceManager.GetString("NoTemplatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Radfordhound/HedgeLib/tree/master/HedgeEdit/Templates.
        /// </summary>
        internal static string TemplatesURL {
            get {
                return ResourceManager.GetString("TemplatesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guest has stopped working!.
        /// </summary>
        internal static string Unknown_InstructionFoundText {
            get {
                return ResourceManager.GetString("Unknown_InstructionFoundText", resourceCulture);
            }
        }
    }
}
